Graviti-AI/tensorbay-python-sdk

tensorbay/client/dataset.py, tensorbay/client/gas.py, tensorbay/dataset/segment.py, tensorbay/label/attributes.py, tensorbay/label/label.py, tensorbay/utility/tbrn.py
changed files:
- client.dataset.py
- client.gas.py
- label.attributes.py
- label.label.py
- utility.tbrn.py
- dataset.segment.py
=> docs: correct docstring of 6 files

docs/source/examples/audio-sentence.rst, docs/source/examples/image-box2d.rst, docs/source/examples/image-keypoints2d.rst, docs/source/examples/point_cloud-box3d.rst, docs/source/examples/text-classification.rst, docs/source/features/tensorbay_client.rst, docs/source/quick_start.rst, tensorbay/client/cli.py, tensorbay/client/dataset.py, tensorbay/client/gas.py
1.Rename "list_segments" to "list_segment_names" 
2.Rename "list_datasets" to "list_dataset_names"﻿
=> refactor(client): rename "list_segments" and "list_datasets"

docs/source/basic_concepts.rst, docs/source/features.rst, docs/source/features/create_and_upload_dataset.rst, docs/source/features/read_dataset.rst, docs/source/features/tensorbay_client.rst, docs/source/features/upload_dataset.rst, docs/source/features/version_control.rst
changed files:
- basic_concepts
- features
- features/create_and_upload_dataset
- features/read_dataset
- features/upload_dataset
- features/tensorbay_client
- features/version_control
=> docs: refine the contents of "Basic Concepts" and "Features" chapters

docs/source/features/tensorbay_client.rst
- correct methods' names.
- deprecate boldface format.
=> docs: refine the contents of "TensorBay Client" chapter

docs/source/tensorbay_cli/dataset_management.rst, docs/source/tensorbay_cli/getting_started_with_cli.rst
Changed files includes tensorbay_cli/dataset_management.rst and getting_started_with_cli.rst
=> docs: refactor "TensorBay CLI" chapter

examples/bstld.py
use own dataloader instead of the one from SDK in "Upload Dataset" in bstld.py
=> docs: remove redundant code in "Upload Dataset" of examples/bstld.py

docs/source/examples/BSTLD.rst
move "commit" related description from "Read Dataset" to "Upload Dataset"
=> docs: move the "commit" related part to "Upload Dataset" in BSTLD.rst

docs/source/reference/glossary.rst
add "continuous" related content to "dataset" and "fusion dataset"
in glossary.rst
=> docs: add "continuous" related content to glossary.rst

tensorbay/label/attributes.py, tensorbay/label/basic.py, tensorbay/label/label_box.py, tensorbay/label/label_keypoints.py, tensorbay/label/label_polygon.py, tensorbay/label/label_polyline.py, tensorbay/label/label_sentence.py, tensorbay/label/supports.py, tensorbay/utility/name.py
in the following classes:
- NameMixin
- KeypointsInfo
- SubcatalogBase
=> refactor: change "description" from class variable to instance variable

tensorbay/client/gas.py, tensorbay/client/requests.py
1.Realize the function of getting ang listing AuthStorageConfigs
2.Modify the logic of open url maker.
=> feat(client): adapt openapi "ListAuthStorageConfigs"

tensorbay/client/gas.py
1.Add function "create_dataset_with_auth_storage".
=> feat(client): support creating dataset in auth storage

tensorbay/client/requests.py, tensorbay/client/segment.py
Now support reading and uploading data from Intranet through
passing params "isInternal".
=> feat(client): support reading and uploading data from internal

.pre-commit-config.yaml
D100 Missing docstring in public module
=> ci: ignore flake8 "D100" error for "tensorbay/opendataset/*"

examples/BSTLD.py, examples/CADC.py, examples/DogsVsCats.py, examples/LeedsSportsPose.py, examples/NeolixOD.py, examples/Newsgroups20.py, examples/THCHS30.py
change commit message from dataset name to "initial commit"
=> docs(examples): standardize initial commit message as "initial commit"

docs/source/examples/BSTLD.rst, docs/source/examples/read_dataset_class.rst, examples/BSTLD.py
=> docs: refine examples/BSTLD.rst

docs/source/examples/DogsVsCats.rst, examples/DogsVsCats.py
=> docs: refine examples/DogsvsCats.rst

docs/source/examples/LeedsSportsPose.rst, examples/LeedsSportsPose.py
=> docs: refine examples/LeedsSportsPose.rst

docs/source/features/dataset_management.rst
1. Change "open datasets" to "shared `Open Datasets`_ platform".
2. Delete "the key operations towards datasets".
3. Correct step order in Organize Dataset chapter.
4. Change "label meta information" to "label schema information".
5. Change the description of "usages" to  "An organized local dataset can be
used to:..." in Upload Dataset chapter.
6. Change "Use it directly"  to "read it directly"
7. Correct "Read Dataset uplaoded" to "Read Dataset uploaded"
=> docs: refine features/dataset_mamagement.rst

docs/source/examples/THCHS30.rst, examples/THCHS30.py
- add "a" catalog to Write the Catalog part
=> docs: refine examples/THCHS30.rst

docs/source/examples/NeolixOD.rst, examples/NeolixOD.py
- add "a" catalog to Write the Catalog part
=> docs: refine examples/NeolixOD.rst

docs/source/examples/Newsgroups20.rst, examples/Newsgroups20.py
- add "a" catalog to Write the Catalog part.
- delete "List Dataset Names" part.
- add step number to "Organize Dataset".
- add code of regular import in writing dataloader.
- add use of available dataloaders.
- polish the description, reduce meaningless sentences.
=> docs: refine examples/NewsGroup20.rst

docs/source/examples/BSTLD.rst, docs/source/examples/DogsVsCats.rst, docs/source/examples/LeedsSportsPose.rst, docs/source/examples/NeolixOD.rst, docs/source/examples/Newsgroups20.rst, docs/source/examples/THCHS30.rst
add note to:
- BSTLD.rst
- DogvsCats.rst
- LeedsSportsPose.rst
- NeolixOD.rst
- Newsgroups20.rst
- THCHS30.rst
=> docs: explain that catalog is provided when using imported dataloaders

tensorbay/client/__init__.py, tensorbay/client/dataset.py, tensorbay/client/exceptions.py, tensorbay/client/gas.py, tensorbay/client/requests.py, tensorbay/client/segment.py, tensorbay/exception.py, tests/test_datasetclient.py, tests/test_gas.py
- AccessDeniedError
- InvalidParamsError
- NameConflictError
- RequestParamsMissingError
- ResourceNotExistError
- ResponseSystemError
- UnauthorizedError
=> feat(exception): implement the specific exceptions of ResponseError

tensorbay/label/supports.py, tensorbay/label/tests/test_supports.py
- `CategoriesMixin.get_category_to_index()`
- `CategoriesMixin.get_index_to_category()`
=> feat(label): add getting category & index conversions in CategoriesMixin

docs/source/reference/exception.rst, tensorbay/exception.py
- AccessDeniedError
- InvalidParamsError
- NameConflictError
- RequestParamsMissingError
- ResourceNotExistError
- ResponseSystemError
- UnauthorizedError
=> docs: add documents for specific response exceptions

tensorbay/cli/cli.py, tensorbay/cli/dataset.py
use the name rather than tbrn to create dataset in "gas dataset" command
=> refactor(cli): use name instead of TBRN to create dataset by gas dataset

tensorbay/sensor/intrinsics.py
- CameraMatrix
- DistortionCoefficients
- CameraIntrinsics
=> refactor(sensor): inherit EqMixin and remove __eq__ in intrinsic classes

tensorbay/cli/cli.py, tensorbay/cli/dataset.py
Basically this reverts commit 088736546f2a294742a4bd8c18614aa9d708a2b6.
=> refactor(cli): use TBRN instead of name to create dataset by gas dataset

tensorbay/client/dataset.py
Issue Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/issues/579
=> fix(client): fix AttributeError when resuming upload of fusion dataset

tensorbay/sensor/intrinsics.py, tensorbay/sensor/tests/test_intrinsics.py, tests/test_sensor.py
- Use dynamic attr for `distortion_coefficients` in `CameraIntrinsics`
- Change private attrs to public attrs in `CameraIntrinsics`
=> refactor(sensor): use dynamic attr and public attrs in CameraIntrinsics

docs/code/draft_and_commit.py, docs/source/features/version_control.rst, docs/source/reference/glossary.rst, docs/source/version_control/draft_and_commit.rst
1. remove "linear version control" description in version_control.rst
2. modify content about creating draft in draft_and_commit.rst
3. modify content about branch and draft in glossary.rst
=> docs: update version control chapter based on newly added Branch section

tensorbay/geometry/tests/test_vector.py, tensorbay/geometry/vector.py
implement below methods:
- `Vector.__sub__`
- `Vector.__rsub__`
- `Vector.__mul__`
- `Vector.__rmul__`
- `Vector.__truediv__`
- `Vector.__floordiv__`
=> feat(geometry): add basic arithmetic methods for "Vector"

tensorbay/client/requests.py, tensorbay/client/tests/test_requests.py
Results:
| method         | before           | after             |
| -------------- | ---------------- | ----------------- |
| `__iter__`     | 629 ns ± 21.5 ns | 279 ns ± 30.6 ns  |
| `__reversed__` | 638 ns ± 25.2 ns | 256 ns ± 15.3 ns  |
| `__contains__` | 5.81 ms ± 108 µs | 1.55 ms ± 8.22 µs |
| `__iadd__`     | 4.02 µs ± 576 ns | 1.78 µs ± 89.1 ns |
| `index`        | 5.7 ms ± 73 µs   | 1.99 ms ± 47.1 µs |
| `count`        | 5.82 s ± 7.8 ms  | 1.59 s ± 14.7 ms  |
| `reverse`      | 12.8 s ± 28.6 ms | 5.3 ms ± 186 µs   |
| `append`       | 1.12 µs ± 31 ns  | 735 ns ± 94.7 ns  |
| `extend`       | 4.1 µs ± 659 ns  | 2.09 µs ± 234 ns  |
| `pop`          | 1.33 µs ± 150 ns | 600 ns ± 43.1 ns  |
=> perf(client): override PagingList Mixin methods from "MutableSequence"

docs/source/reference/label_format.rst, tensorbay/dataset/dataset.py, tensorbay/healthcheck/catalog_check.py, tensorbay/label/catalog.py, tensorbay/label/label_box.py, tensorbay/label/label_classification.py, tensorbay/label/label_keypoints.py, tensorbay/label/label_polygon.py, tensorbay/label/label_polyline.py, tensorbay/label/label_sentence.py, tensorbay/label/supports.py, tensorbay/label/tests/conftest.py, tensorbay/opendataset/CompCars/loader.py, tensorbay/sensor/sensor.py, tensorbay/utility/__init__.py, tensorbay/utility/attr.py, tensorbay/utility/name.py
`NamedList` -> `NameList`
`NameSortedList` -> `SortedNameList`
=> refactor(utility): rename "NamedList" and "NameSortedList"

tensorbay/utility/name.py, tensorbay/utility/user.py
Add following functions:
- `UserSequence.__contains__`
- `NameList.__contains__`
- `SortedNameList.__contains__`
=> feat(utility): add "__contains__" for "Sequence" subclasses

tensorbay/dataset/dataset.py, tensorbay/dataset/tests/test_dataset.py
Add `DatasetBase.__contains__` to check whether the dataset contains the
segment with the given name
=> feat(dataset): add "DatasetBase.__contains__"

tensorbay/client/gas.py, tensorbay/client/struct.py, tensorbay/client/tests/test_gas.py, tensorbay/client/tests/test_struct.py, tests/test_branch.py, tests/test_commit.py, tests/test_dataset.py, tests/test_tag.py
Change the following attrs to dynamic in `Branch`:
- parent_commit_id
- title
- description
- committer
=> refactor(client): adapt branch without commit history in Branch

.pre-commit-config.yaml
`yamllint` and `prettier` will help check yaml files, `check-yaml` is
redundant.
=> ci: update basic "pre-commit-hooks" to "v4.0.1" and remove "check-yaml"

tensorbay/label/basic.py
PR Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/pull/751
=> fix(label): add a workaround to support the wrong label platform format

tests/test_move_and_copy.py
1. test move segment override
2. test move segment skip
3. test copy segment override
4. test copy segment skip
5. test copy data from another dataset
5. test copy data from previous commit
=> test: add six test cases for move and copy operation

tensorbay/opendataset/CADC/loader.py, tensorbay/opendataset/LISATrafficLight/loader.py, tensorbay/opendataset/nuScenes/loader.py
The legal segment name can't contain ASCII control characters
(less than \040 or \177 DEL), spacewhite, ~, ^,:,?, *, [, \, /, @.
=> fix(opendataset): correct the illegal segment name

.github/CODEOWNERS
=> chore: change the owner of "/docs/" in CODEOWNERS

tensorbay/cli/config.py, tensorbay/cli/utility.py
Gas config supports setting is_internal,
max_retries, and timeout in request config.
=> feat(cli): add support for setting request config in "gas config"

tensorbay/opendataset/VOC2012ActionClassification/loader.py, tensorbay/opendataset/VOC2012Detection/loader.py
correct the catalog paths for VOC2012Detection and VOC2012ActionClassification
=> fix(opendataset): correct wrong catalog paths for two VOC2012 datasets

tensorbay/label/attributes.py
Attr "name" is displayed in AttributeInfo._repr_head
=> refactor(label): remove "name" from "AttributeInfo._repr_attrs"

docs/source/reference/label_format.rst
Contains the following types:
- Polygon
- MultiPolygon
- RLE
- Polyline2D
- MultiPolyline2D
=> docs: add five label types in label_format.rst

tensorbay/client/segment.py, tensorbay/dataset/data.py, tensorbay/dataset/frame.py, tensorbay/dataset/tests/test_data.py, tensorbay/dataset/tests/test_frame.py, tensorbay/utility/file.py
BREAKING CHANGE: `RemoteData.dumps` and `Frame.dumps` is removed
=> refactor!: add "get_callback_body" to replace "dumps" in "RemoteData"

tensorbay/opendataset/BDD100K/catalog_10k.json, tensorbay/opendataset/BDD100K/loader.py
read BDD100K_10K labels only from pan_seg polygons and change
BDD100K_10K labels from polygon and polyline2d to only polygon
=> refactor(opendataset): read pan_seg polygon as the labels of BDD100K_10K

tensorbay/opendataset/VOC2012ActionClassification/loader.py, tensorbay/opendataset/VOC2012Detection/loader.py
process input paths with "abspath" and "expanduser"
=> fix(opendataset): correct input paths for two VOC2012 datasets

.github/CODEOWNERS
- `/docs/`: @Lee-000 -> @graczhual
- `/tensorbay/client/`: @rexzheng324-c -> @AChenQ
=> chore: change the code owners of "/docs/" and "/tensorbay/client/"

tensorbay/cli/tests/test_dataset.py, tensorbay/cli/tests/test_draft.py, tensorbay/cli/tests/test_ls.py
"modify "test_dataset.py", "test_draft.py" and "test_ls.py""
=> test(cli): use assert_cli_success and assert_cli_fail uniformly in cli

tensorbay/cli/__init__.py, tensorbay/cli/cli.py, tensorbay/cli/custom.py, tensorbay/cli/tbrn.py, tensorbay/cli/utility.py
modify "cli.py", "custom.py", "tbrn.py", "utility.py" and "__init__.py"
=> docs(cli): update module docstring for cli

tensorbay/opendataset/_utility/mocker.py
The error message:
```
[Pyright reportOptionalSubscript] [E] Object of type "None" is not subscriptable
```
=> refactor(opendataset): return Any in mocker to avoid pyright error

tensorbay/opendataset/BDD100K/catalog_100k.json, tensorbay/opendataset/BDD100K/loader.py
remove the "areaType" of "POLYGON" and the "laneTypes" of "POLYLINE2D"
=> refactor(opendataset): remove relucdant attributes of BDD100K dataset

tensorbay/cli/log.py
The wrong example:
```
* | | commit d7677e0abd1e4de1a0a4e153948b3437
| | | Author: algorithm team
| | | Date: Mon Nov 15 16:57:37 21
| | |
| | |     4
| | |
* | | commit e1d77c419bbf4954848565d2ecbd7b08
|/ /  Author: algorithm team
|     Date: Mon Nov 15 16:57:36 21
|
|         3
|
| | * commit f4783410d62d4fcd8a91e8d12036c3da (b4)
| |/  Author: algorithm team
| |   Date: Mon Nov 15 16:57:44 21
| |
| |       9
| |
| * commit dc2a3cc9f3ae4cb3906587fb6420fb87
|/  Author: algorithm team
|   Date: Mon Nov 15 16:57:39 21
|
|       5
|
```
Fixed:
```
* | | commit d7677e0abd1e4de1a0a4e153948b3437
| | | Author: algorithm team
| | | Date: Mon Nov 15 16:57:37 21
| | |
| | |     4
| | |
* | | commit e1d77c419bbf4954848565d2ecbd7b08
|/ /  Author: algorithm team
| |   Date: Mon Nov 15 16:57:36 21
| | …
```
=> fix(cli): fix the wrong graph in "gas log --graph" when merging branches

tensorbay/opendataset/nuImages/catalog.json
"vehicle_position" -> "vertical_position"
=> fix(opendataset): correct wrong attribute name in nuImages catalog
