tensorbay/dataset/segment.py
tensorbay/label/attributes.py
tensorbay/label/supports.py
tensorbay/sensor/sensor.py
tensorbay/utility/name.py

The class "Dataset" is the subclass of NameMixin, but "Dataset" does not
support "dumps" methods yet. Make "NameMixin.dumps()" private to make
sure "dumps" can not be called from "Dataset"

refactor(utility): make "NameMixin.dumps()" private

---

docs/source/api_reference.rst
docs/source/examples.rst
docs/source/index.rst
docs/source/quick_start.rst
docs/source/supported_label_types.rst

changed files:
- tensorbay_sdk_api -> api_reference
- change file name
- change title
- examples
- change content
- index
- change content
- change title
- remove redundant comment
- quick_start
- change content
- supported_label_types
- change content

docs: refine the titles, contents and comments of 5 chapters

---

tensorbay/sensor/intrinsics.py

Change the keyword argument "is_fisheye" to positional argument in "DistortionCoefficients.distort()".﻿

fix(sensor): change is_fisheye to positional argument in distort method

---

tensorbay/sensor/intrinsics.py

Only require tangential or radial distortion to initialize `Distortion﻿Coefficients`.

fix(sensor): require tangential or radial distortion to init distortion

---

tensorbay/client/requests.py

1.Now setting parameters when initing the config instance is not allowed. If you want to modify the parameters, "default_config.param = .." is permitted.
2.Add allowed_retry_methods and allowed_retry_status in config to support deploying personal retry strategy.

feat(client): support setting allowed retry parameter in class Config

---

docs/source/reference/label_format.rst
tensorbay/dataset/frame.py
tensorbay/geometry/box.py
tensorbay/geometry/tests/test_box.py
tensorbay/geometry/tests/test_transform.py
tensorbay/geometry/transform.py
tensorbay/label/label_box.py
tensorbay/label/tests/test_label_box.py
tensorbay/opendataset/DeepRoute/loader.py
tensorbay/opendataset/NeolixOD/loader.py
tensorbay/sensor/intrinsics.py
tensorbay/sensor/sensor.py
tensorbay/sensor/tests/test_intrinsics.py
tensorbay/sensor/tests/test_sensor.py
tensorbay/utility/__init__.py
tensorbay/utility/common.py

- Use "matrix" keyword argument in __init__() of Transfrom3D and CameraMatrix.
- No longer support init from self in Transfrom3D.

refactor: use matrix as keyword arg to init Transfrom3D and CameraMatrix

---

tensorbay/client/segment.py
tensorbay/dataset/frame.py

If user use a "str" rather than "ULID" to initialize a Frame, the
"frame_id" will be a "str". Type "str" does not have ".str" property,
but function "str()" supports both "str" and "ULID". This makes
"Frame.dumps()" and "FusionSegmentClient.upload_frame()" work correctly
even if the "frame_id" is a "str"

feat(dataset): use str() instead of ULID.str to transform ULID to str

---

requirements.txt

related issue:
https://github.com/PyCQA/pylint/pull/4334

ci: set astroid version==2.5.2 to fix pylint false positive

---

.github/workflows/pre-commit.yaml
.github/workflows/test_unit.yaml

rollback commit: 4b6ef7d
reason:
if not set version for rely packages, github actions cache will auto upgrade it

ci: rollback github actions cache path to absolute path

---

tensorbay/client/requests.py

SSL may raise error when reusing the same session for multiprocesses
related issue:
https://github.com/psf/requests/issues/4323

feat(client): make session safe in multiprocesses environment

---

examples/draft_and_commit.py
tensorbay/client/dataset.py
tests/test_datasetclient.py

There are different ways to name a commit object, such as commit id,
branch name or tag name. The word "revision" is been chosen to represent
all these names of a commit.

refactor(client): rename "commit_key" to "revision"

---

tests/test_datasetclient.py
tests/test_gas.py
tests/test_segmentclient.py

1. Set sleep time after calling asynchronous api.(Now ignore)
2. Adapt with the check function in "datasetClient.checkout()".
3. No longer check the equility of input and outpust sensor.(Now ignore)

test(client): fix incorrect raise and mark known failed case as "xfail"

---

tensorbay/opendataset/AnimalPose/loader.py
tensorbay/opendataset/BioIDFace/loader.py
tensorbay/opendataset/DeepRoute/loader.py
tensorbay/opendataset/DogsVsCats/loader.py
tensorbay/opendataset/ImageEmotion/loader.py
tensorbay/opendataset/LISATrafficLight/loader.py
tensorbay/opendataset/LeedsSportsPose/loader.py
tensorbay/opendataset/NeolixOD/loader.py
tensorbay/opendataset/Newsgroups20/loader.py

TensorBay2.3 Standard:
`name` is the unique identifier of a dataset, which is used for generating
`url` and dataset retrieval in TensorBay SDK, CLI and OpenAPI. It can only be
composed of letters, numbers, `-` and `_`.

docs(opendataset): adapt name in dataloaders to Tensorbay2.3 standard

---

docs/source/tensorbay_cli/getting_started_with_cli.rst

- delete redundant description for "gas config"
- polish description for accessKey

docs: refine "Configuration" of "getting_started_with_cli.rst"

---

docs/source/version_control/draft_and_commit.rst
docs/source/version_control/tag.rst
examples/draft_and_commit.py
examples/tag.py

draft_and_commit.rst:
- description of Client
- simplify  the explanation of draft and commit, and add links to
glossary
- change the links of classes to the links of glossary
- correct the title "Draft And Commit" as "Draft and Commit"
- change the title "Before Use" as "Authorization"
- correct the order of notation and code in draft_and_commit.py
- "... is simple" -> "supports"
- delete redundant description
tag.rst:
- "has the ability to" -> supports
- mark release points -> mark release revision
- do not commit after creating a dataset in tag.py
- add the third way to create tag
- delete redundant description

docs: refine version control section in draft_and_commit.rst and tag.rst

---

tensorbay/client/requests.py
tensorbay/exception.py

1. Use the word "Unexpected" rather than "Invalid".
2. Fix the typo "state code" to "status code".
3. Remove "self.status_code" and use "self.response.status_code" instead

refactor: refine the error message of unexpected status code

---

tensorbay/opendataset/AnimalPose/loader.py
tensorbay/opendataset/AnimalsWithAttributes2/loader.py
tensorbay/opendataset/BioIDFace/loader.py
tensorbay/opendataset/CarConnection/loader.py
tensorbay/opendataset/CoinImage/loader.py
tensorbay/opendataset/DeepRoute/loader.py
tensorbay/opendataset/DogsVsCats/loader.py
tensorbay/opendataset/DownsampledImagenet/loader.py
tensorbay/opendataset/Elpv/loader.py
tensorbay/opendataset/FSDD/loader.py
tensorbay/opendataset/Flower/loader.py
tensorbay/opendataset/HalpeFullBody/loader.py
tensorbay/opendataset/HardHatWorkers/loader.py
tensorbay/opendataset/HeadPoseImage/loader.py
tensorbay/opendataset/ImageEmotion/loader.py
tensorbay/opendataset/JHU_CROWD/loader.py
tensorbay/opendataset/KenyanFood/loader.py
tensorbay/opendataset/KylbergTexture/loader.py
tensorbay/opendataset/LISATrafficLight/loader.py
tensorbay/opendataset/LeedsSportsPose/loader.py
tensorbay/opendataset/NeolixOD/loader.py
tensorbay/opendataset/Newsgroups20/loader.py
tensorbay/opendataset/WIDER_FACE/loader.py

TensorBay2.3 Standard:
`name` is the unique identifier of a dataset, which is used for generating
`url` and dataset retrieval in TensorBay SDK, CLI and OpenAPI. It can only be
composed of letters, numbers, `-` and `_`.

docs(opendataset): amend names in dataloaders to Tensorbay2.3 standard

---

tensorbay/client/dataset.py

Exception Info:
UnboundLocalError: local variable 'commit' referenced before assignment

fix(client): fix UnboundLocalError when calling create_tag with revision

---

docs/source/advanced_features/fusion_dataset.rst
docs/source/examples/read_dataset_class.rst
docs/source/features/dataset_management.rst
docs/source/quick_start/getting_started_with_tensorbay.rst

Modified Contents:
1. Change "this page" to specific description.
2. Change "this part" to specific description.
3. Delete unnecessary cross-references.
4. Deprecate "(ref)" style cross-references and hyperlinks.

docs: modify cross-references and hyperlinks in related rst files

---

tensorbay/opendataset/HalpeFullBody/catalog.json
tensorbay/opendataset/HalpeFullBody/loader.py

the label format of Box2D is not uniform in the dataset
issue link: https://github.com/Fang-Haoshu/Halpe-FullBody/issues/4
annotations for "hoi" in Classification label lack important
information

fix(opendataset): remove Classification and Box2D label in HalpeFullBody

---

tensorbay/sensor/sensor.py

Resolve the issue that KeyError raised when calling:
`segment = FusionSegment("", dataset_client)`
Issue Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/issues/455

fix(sensor): only loads intrinsics and extrinsics with valid value

---

.pre-commit-config.yaml

- isort: v5.7.0 -> v5.8.0
- black: 20.8b1 -> 21.4b0
- flake8: 3.8.4 -> 3.9.1
- markdownlint-cli: v0.26.0 -> v0.27.1

ci: update linters: "isort", "black", "flake8" and "markdownlint-cli"

---

tensorbay/client/gas.py

Arguments "start" and "stop" in list method is deprecated in v1.3.0.

refactor(client): remove start & stop args in list_auth_storage_configs

---

docs/source/advanced_features/request_configuration.rst
docs/source/advanced_features/use_internal_endpoint.rst
examples/request_configuration.py
examples/use_internal_endpoint.py

Refine contents as below:
1. Change import path of "config" from "requests" to "client" in code block.
2. Use general uploading process instead specific dataset example in code block.
3. Change the description of purpose of "Usage" in "Use Internal Endpoint".

docs: refine "Usage" in request configuration related docs

---

tensorbay/client/dataset.py
tensorbay/dataset/dataset.py
tensorbay/dataset/segment.py

Change the signature of `Dataset.__init__` from:
```python
def __init__(self, name: str) -> None:
````
to:
```python
def __init__(self, name: str, gas: Optional["GAS"] = None) -> None:
````
Usage:
```python
gas = GAS("AccessKey-xxxx")
dataset = Dataset("DatasetName", gas)
```
The returned dataset is a lazy evaluation Dataset which will request for
the data when user accesses them instead of requesting everything when
initialization.

feat(client): support getting a lazy evaluation Dataset from __init__

---

tensorbay/client/dataset.py

The `commit_id` in `DatasetClientBase.__init__` is always from
the `getDataset` request in `GAS.get_dataset`, which means the
validation of the `commit_id` is guaranteed by OpenAPI.

perf(client): stop checking the commit_id in DatasetClientBase.__init__

---

tensorbay/dataset/segment.py
tensorbay/utility/repr.py

Root Cause:
`ReprMixin.__repr__` will check `len(obj)` to print `[]` or `[...]`
But in `PagingList` lazy evaluation system, if the obj is not
initialized, `len(obj)` will send request for the totalCount, which may
cause a lot of requests just for print.
Workaround:
Add a flag `_repr_non_empty` to make `ReprMixin` skip checking
the `len(obj)` and always print `[...]`

perf(dataset): treat Segment init from client non-empty in ReprMixin

---

README.md
docs/source/examples/read_dataset_class.rst
examples/BSTLD.py
examples/CADC.py
examples/DogsVsCats.py
examples/LeedsSportsPose.py
examples/NeolixOD.py
examples/Newsgroups20.py
examples/THCHS30.py
examples/getting_started_with_tensorbay.py

`Dataset.__init__` is supported to get a lazy evaluated `Dataset`
It will be more pythonic to get a `Segment` instance from `Dataset`
rather than `DatasetClient`

docs: get Segment instance from Dataset rather than DatasetClient

---

docs/source/features/dataset_management.rst

1. add the example cross-references in Read Dataset part of Dataset
Management
2. format the example cross-references in Update Dataset part of Dataset
Management

docs: standardize the example cross-references in Dataset Management

---

tensorbay/client/gas.py

The method `gas.upload_dataset()` will log the resume error message when
the upload got interrupted.
But when `draft_number` parameter is not given,
the logging of resume error message will raise
`TypeError: %d format: a number is required, not NoneType`.

fix(client): fix the TypeError when uploading dataset got interrupted

---

tensorbay/client/requests.py
tensorbay/client/segment.py
tensorbay/dataset/dataset.py
tensorbay/utility/common.py

Root Cause:
The `threading.Lock` object cannot be pickled. The `threading.Lock` is
widely used in `Dataset` to avoid sending redundant requests. So that
putting `Dataset` in multiprocess pool will hit the TypeError caused by
`threading.Lock`:
```python
TypeError: cannot pickle '_thread.lock' object
```
Solution:
Remove all the `theading.Lock` member in `Dataset`, and use a lock pool
to dynamicly create `threading.Lock` when sending request.

fix(client): fix the TypeError when put Dataset in multiprocess pool

---

tensorbay/cli/cli.py
tensorbay/cli/commit.py
tensorbay/cli/draft.py
tensorbay/cli/rm.py
tensorbay/cli/utility.py

1. Add "\f" at the end of introduction of function in cli.py.
2. Adjust double quotes in echo message in commit.py, rm.py and draft.py.
3. Add missing period in utility.py.
4. Capitalize the first character in echo message in utility.py

fix(cli): adjust docstring and echo message in 5 files

---

tensorbay/client/requests.py
tensorbay/exception.py

Root Cause:
When the status code of a response is unexpected, the custom
`ResponseError` would be raised.
`ResponseError` would use `response.json()` to get the content of the
failed response.
If the failed response is not from OpenAPI, the "Content-Type" may not
be "application/json" which causes `JSONDecodeError` when executing
`response.json()`.
Solution:
- Use `response.text` instead of `response.json()` to get the
response content in `ResponseError`.
- Only use `response.json()` to get the error code in `Client.open_api_do()`.
Issue Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/issues/562

fix(client): fix JSONDecodeError when failed response not from OpenAPI

---

tensorbay/cli/utility.py

Root Cause:
`tensorbay/cli/utility.py` import `Literal` from `typing`, but `Literal`
is added to `typing` in python3.8, which causes the `ImportError`:
```python
ImportError: cannot import name 'Literal'
```
Solution:
Import `Literal` from `typing_extensions`

fix(cli): fix ImportError when executing gas CLI in python3.6 and 3.7

---

tensorbay/opendataset/CADC/loader.py

Root Cause:
`datetime.datetime.fromisoformat` is not available in python version
before 3.7.
Solution:
Use `datetime.datetime.striptime` instead of
`datetime.datetime.fromisoformat` to get the timestamp.
Issue Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/issues/574

fix(opendataset): fix datetime AttributeError using CADC in python3.6

---

tensorbay/utility/attr.py

`attr()` returns `Field` as the class variables value, using type hint
as the real type of variables.
pylint use `Field` as the variable type, so it will report the following
errors
`E0237: Assigning to attribute 'box2d' not defined in class slots
(assigning-non-slot)`
`E1101: Instance of 'Field' has no 'box3d' member (no-member)`
do the following as a workaround for pylint errors
* remove `__slot__` for E0237
* add `__getattr__` function for E1101
related issue:
https://github.com/PyCQA/pylint/issues/4341

refactor(utility): modify "AttrsMixin" as a workaround for pylint errors

---

docs/source/integrations/pytorch.rst
docs/source/integrations/tensorflow.rst

"Integrate TensorBay with TensorFlow" -> "TensorFlow"
"Integrate TensorBay with PyTorch" -> "PyTorch"

docs: shorten titles of docs under integrations.rst

---

tensorbay/client/dataset.py

Errors in mypy:
```
tensorbay/client/dataset.py|708 col 29 error
Incompatible types in assignment(expression has type "float",
variable has type "Optional[int]")[assignment]
tensorbay/client/dataset.py|709 col 41 error
Argument 1 to "get" of "Mapping" has incompatible type "Optional[int]";
expected "float"[arg-type]
```

style(client): fix mypy errors in FusionDatasetClient._skip_upload_frame

---

tensorbay/utility/attr.py

Mypy does not raise an error on a `missing method` when base class
defines a `__getattr__` function, so make mypy ignore that method
by decorating `__getattr__` with `typing.no_type_check`.
related issue: https://github.com/python/mypy/issues/6251

style(utility): do not check the type of "__getattr__" in "AttrsMixin"

---

tensorbay/dataset/dataset.py
tensorbay/utility/name.py

`DatasetBase` inherits from classes `Sequence[_T]` and `NameMixin`,
When the `NameMixin` is before `Sequence[_T]`, `typing` will raise
`AttributeError`.
related issue : https://github.com/python/typing/issues/777

refactor(utility): use "AttrsMixin" in "NameMixin"

---

tensorbay/cli/ls.py

add info to "gas ls" when dataset has no commit ID and draft number

feat(cli): add error info to "gas ls" when dataset has no commit history

---

tensorbay/utility/user.py

Root Cause:
The default value of `stop` argument is `-1`, which will skip the last
item when checking the index.
Solution:
Change the default value of `stop` to `maxsize`
Issue Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/issues/610

fix(utility): fix ValueError passing the last item to UserSequence.index

---

tensorbay/dataset/data.py

Root Cause:
When opening the url containing chinese character, `UnicodeEncodeError`
will be raised, because `urlopen` only handle with url containing ASCII
code.
Solution:
Here using `urllib.parse.quote` to convert the chinese character.
Issue Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/issues/676

fix(dataset): fix UnicodeEncodeError when urlopen with chinese character

---

tensorbay/geometry/polyline.py
tensorbay/geometry/tests/test_polyline.py

Modifications:
1. Stop using the numpy array.
2. Use `math.dist` to calculate the distance of two vector.
3. Use `tuple` instead of `list` when possible.
4. Use more generator and iterator.
5. Simply the calculation logic.
Target: enhance the performance of the following methods:
- `Polyline2D.uniform_frechet_distance`
- `Polyline2D.similarity`
Results:
```python
polyline_1 = [[1, 1], [1, 2], [2, 2]]
polyline_2 = [[4, 5], [2, 1], [3, 3]]
```
- before:
```python
>>> %timeit Polyline2D.uniform_frechet_distance(polyline_1, polyline_2)
231 µs ± 2.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit Polyline2D.similarity(polyline_1, polyline_2)
239 µs ± 3.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
- after:
```python
>>> %timeit …
```

perf(geometry): stop using numpy array in "uniform_frechet_distance"

---

docs/source/tensorbay_cli/cli_commands.rst
docs/source/tensorbay_cli/getting_started_with_cli.rst
docs/source/tensorbay_cli/tbrn.rst

<> means a required option and [] means an optional option.

docs: unify the usages of "<>" and "[]" in CLI

---

tensorbay/utility/name.py

`DatasetBase` and `SegmentBase` are subclasses of `NameMixin`, but they
do not support `loads` and `dumps` methods. Remove `loads` and `dumps`
from `NameMixin` to make sure they cannot be called from `DatasetBase`
and `SegmentBase`

refactor(utility): remove "loads" and "dumps" from "NameMixin"

---

tensorbay/client/requests.py

Deprecation warning from requests:
```
DeprecationWarning: Using 'method_whitelist' with Retry is deprecated
and will be removed in v2.0. Use 'allowed_methods' instead
```

refactor(client): use "allowed_methods" instead of "method_whitelist"

---

docs/source/tensorbay_cli/tbrn.rst

change the model of code from "console" to "html"

docs: use "html" instead of "console" in code block introducing TBRN

---

tensorbay/client/cloud_storage.py
tensorbay/client/tests/test_cloud_storage.py
tensorbay/dataset/data.py

- Add `CloudClient.list_auth_data()` to list all the cloud files in
`AuthData` format.
- Use `AuthData.open()` instead of `CloudClient.open()`.
- Remove `list_files()` and open() in `CloudClient`.

feat: add AuthData.open() and CloudClient.list_auth_data()

---

tensorbay/client/segment.py
tests/test_move_and_copy.py

TensorBay backend v2.7 does not support "override" and "skip" strategy
in move data feature.

feat(client): remove "strategy" argument in "move_data" method

---

docs/source/tensorbay_cli/cli_commands.rst
docs/source/tensorbay_cli/getting_started_with_cli.rst
tensorbay/cli/auth.py
tensorbay/cli/cli.py

display error messages when the "profile" entered by user or
the "profiles" section of config file doesn't exist

feat(cli): support displaying error message for "gas auth"

---

tensorbay/client/lazy.py
tensorbay/geometry/point_list.py
tensorbay/sensor/intrinsics.py
tensorbay/utility/attr.py
tensorbay/utility/common.py

-   tensorbay/client/lazy.py:
```python
181: [Pyright reportGeneralTypeIssues] [E] Operator "+" not supported for types
"str | Iterable[str]" and "tuple[Literal['total_count']]"
```
```python
329: [Pyright] [H] "index" is not accessed
```
-   tensorbay/geometry/point_list.py:
```python
43: [Pyright reportInvalidTypeVarUse] [W] TypeVar "\_P" appears only once in
generic function signature
```
```python
126: [Pyright reportInvalidTypeVarUse] [W] TypeVar "\_P" appears only once in
generic function signature
```
-   tensorbay/sensor/intrinsics.py:
```python
325: [Pyright reportGeneralTypeIssues] [E] Operator "\*" not supported for
types "NoReturn" and "float"
```
-   tensorbay/utility/attr.py:
```python
333: [Pyright reportOptionalCall] [E] Object of type "None" cannot be called
```
- …

style: fix the errors, warnings and hints reported by "pyright" 1.1.159

---

tensorbay/client/segment.py
tensorbay/dataset/data.py
tensorbay/dataset/frame.py
tensorbay/dataset/tests/test_data.py
tensorbay/dataset/tests/test_frame.py
tensorbay/utility/file.py

BREAKING CHANGE: The following methods are removed:
- `Data.dumps`
- `RemoteData.dumps`
- `AuthData.dumps`
- `Frame.dumps`

refactor!: add "get_callback_body" to replace "dumps" in "Data"

---

tensorbay/client/segment.py
tensorbay/dataset/data.py
tensorbay/dataset/frame.py
tensorbay/dataset/tests/test_data.py
tensorbay/dataset/tests/test_frame.py

BREAKING CHANGE: The following methods are removed:
- `RemoteData.loads`
- `RemoteData.dumps`
- `Frame.loads`

refactor!: add from_response_body to replace loads in RemoteData & Frame

---

tensorbay/client/diff.py

create the class: "DiffBase", "NotesDiff", "CatalogDiff",
"FileDiff", "LabelDiff", "SensorDiff", "DataDiff", "SegmentDiff" and
"DatasetDiff"

feat(client): add diff-related classes

---

tensorbay/label/label.py
tensorbay/label/label_mask.py

The `loads` and `dumps` methods are removed from mask classes.

refactor(label): add get_callback_body and from_response_body for mask

---

tensorbay/exception.py

Root Cause:
The `__bool__()` of `request.models.Response` returns `self.ok`,
it is `False` when the status code not less than 400. Thus the `response`
attribute of `ResponseError` will never be set.
Solution:
Check whether the `response` argument is `None` or not instead of using
its bool value.

fix(exception): fix AttributeError when calling "ResponseError.response"

---

tensorbay/label/label_mask.py

COCO dataset has panoptic masks with empty info, whose pixel values are
all zeros. When calling `RemotePanopticMask.from_response_body()`,
IndexError may occur.

fix(label): add a workaround for IndexError when load panoptic mask

---

setup.cfg
tensorbay/py.typed

The file "py.typed" tells the type hint checkers like mypy this is a
package supporting typing.
Reference:
- https://www.python.org/dev/peps/pep-0561/
- https://mypy.readthedocs.io/en/stable/installed_packages.html

build: add file "tensorbay/py.typed" to comply with PEP-561

---

tensorbay/cli/log.py

When merging the left branch, the right branch also needs to move to the left
The wrong sample:
```
* 4c564ea (b3) 15
* a3f25ce 13
* ebb775e 8
| * 2da7d6e (b1) 14
| * aeac003 6
| | * 8c9e82e (main) 12
| | | * 1c22915 (b5) 11
| | |/
| |/|
| * | bec94e0 a
| | | * ef0e4c2 (b2) 10
| | | * dee8986 7
| | |/
| |/|
|/| |
* | | d7677e0 4
* | | e1d77c4 3
|/|
| | * f478341 (b4) 9
| |/
| * dc2a3cc 5
|/
* d0eeb20 2
* bce9056 1
```
Fixed:
```
* 4c564ea (* ebb775e 8
| * 2da7d6e (b1) 14
| * aeac003 6
| | * 8c9e82e (main) 12
| | | * 1c22915 (b5) 11
| | |/
| |/|
| * | bec94e0 a
| | | * ef0e4c2 (b2) 10
| | | * dee8986 7
| | |/
| |/|
|/| |
* | | d7677e0 4
* | | e1d77c4 3
|/ /
| | * f478341 (b4) 9
| |/
| * dc2a3cc 5
|/
* d0eeb20 2
* bce9056 1
```

fix(cli): fix the wrong graph in "gas log" when merging branches

---

tensorbay/utility/file.py

When using cache with multiprocess, the result will not necessarily stay
true after asserting `os.path.exists(cache_path) == True`.
Add `exist_ok` when calling `os.makedirs` to fix this problem.

fix(utility): fix the FileExistsError when using cache with multiprocess

---

tensorbay/opendataset/AnimalPose/loader.py
tensorbay/opendataset/HardHatWorkers/loader.py
tensorbay/opendataset/OxfordIIITPet/loader.py
tensorbay/opendataset/VOC2012ActionClassification/loader.py
tensorbay/opendataset/VOC2012Detection/loader.py

Add `Any` typehint for the result of xmltodict.parse() to avoid the
Pyright error.

refactor(opendataset): add typehint for the result of xmltodict.parse()

---

tensorbay/client/profile.py

Raised error details:
`TypeError: do() takes 2 positional arguments but 3 were given`

fix(client): fix the positional arguments error when using profile

---

docs/code/use_dataset_in_paddlepaddle.py
docs/source/integrations/paddlepaddle.rst

Update documentation to resolve pylint duplicate-code error:
```
tensorbay/opendataset/DownsampledImagenet/__init__.py:1:0:
R0801: Similar lines in 2 files
==docs.code.use_dataset_in_paddlepaddle:[17:52]
==docs.code.use_dataset_in_pytorch:[18:52]
```

docs: upadate documentation about "PaddlePaddle" in "INTEGRATIONS"

---

tensorbay/utility/common.py
tensorbay/utility/file.py

When using PyTorch dataloader with multiple workers, the cache file will
be accessed by different processes. And the cache file can be written
and read at the same time, which would lead to the read content being
empty.
Thus, use a temp filename while writing the cache file and then change
it to the cache path. And add a lock to avoid repeatedly writing cache.

fix(utility): add lock for cached file between processes

---

tensorbay/utility/common.py
tensorbay/utility/file.py

The default start method of multiprocessing on Windows is "spawn", which
need to use `main` to protect the entry point. And "fork" is not
supported on Windows.
Beside, the cache path need to add pid to avoid conflict "mv" operation.

refactor(utility): remove multiprocess lock and add pid to cache path

---

tensorbay/geometry/point_list.py
tensorbay/geometry/polygon.py
tensorbay/geometry/tests/test_keypoint.py
tensorbay/geometry/tests/test_polygon.py
tensorbay/geometry/tests/test_polyline.py

When init pointlist related classes with numpy array, ValueError will be
raised:
```
ValueError: The truth value of an array with more than one element is
ambiguous. Use a.any() or a.all()
```

fix(geometry): fix the ValueError when init point list with numpy array

---

tensorbay/utility/repr.py

1. add type hint to variable "class_" to remove the pyright warning
2. remove useless pylint disable "protected-access"

style(utility): add type hint and remove pylint comment in "repr._repr1"
